### PR TITLE
Libretro core Windows fix

### LINKED ISSUE #25: Commit 9bd3628ca broke libretro core on Windows
Hi,

It appears that commit 9bd3628ca broke the libretro core on Windows - loading any game through RA gives the error in log:

```
[INFO] [Video]: Set video size to: 1920x1920.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_w".
[INFO] [Vulkan]: Detecting screen resolution: 3840x2160.
[INFO] [Vulkan]: Found GPU at index 0: "NVIDIA GeForce RTX 3070".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "NVIDIA GeForce RTX 3070".
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1920x1920.
[INFO] [Vulkan]: Using BGRA8888 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: Loading favorites file: "D:\RetroArch\content_favorites.lpl".
Java app is not running anymore! Last known PID=
```
after and then RA crashed.

### PR DESCRIPTION
**Pull request by raidenii**
Fixes #25

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
If you rebase on upstream devel branch, CI will upload an artifact for this PR, makes it easier to test for others.

**Comment by raidenii** [comment]
Is this the corresponding CI build?
https://github.com/TASEmulators/freej2me-plus/actions/runs/11574364755

I don't think it builds libretro cores though, so not sure how it would help here.

**Comment by vadosnaprimer** [comment]
Isn't `freej2me-lr.jar` the file you need? It uploaded it fine after you pulled.

https://github.com/TASEmulators/freej2me-plus/actions/runs/11579312895/artifacts/2119080902

**Comment by raidenii** [comment]
No, not really - my commit only deals with freej2me_libretro.c, and the workflow does not build that. I tested it locally myself though on both win32 and linux.

**Comment by AShiningRay** [comment]
> Isn't `freej2me-lr.jar` the file you need? It uploaded it fine after you pulled.
> 
> https://github.com/TASEmulators/freej2me-plus/actions/runs/11579312895/artifacts/2119080902

Java CI won't get those libretro core changes at all, since nothing was changed in the java side, only the C core... i guess we could implement a CI for libretro later, but it's not a priority right now (especially since i don't have a windows machine at the moment so actual testing there will be lacking, as can be seen by this PR).

Now for the PR itself: Amazing work! Seems A-OK on my linux machine as well.

**Review by AShiningRay — APPROVED** [review]
Looks good to me, also made things more readable (at least to me).

**Review by AShiningRay — APPROVED** [review]
Fine by me as well, no complaints.

**Comment by AShiningRay** [comment]
Well the rest is just cosmetic so i don't see a need to add reviews to them, but they're also fine. Merging since i've found no issues with it. If anything arises on linux (unlikely), i can handle them over here. Thanks a bunch!

**Pull request merged**
